// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Card documents */
interface CardDocumentData {
    /**
     * title field in *Card*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: card.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * description field in *Card*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: card.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * link field in *Card*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: card.link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    link: prismicT.KeyTextField;
    /**
     * image field in *Card*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: card.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Card document from Prismic
 *
 * - **API ID**: `card`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CardDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<CardDocumentData>, "card", Lang>;
/** Content for Config documents */
interface ConfigDocumentData {
    /**
     * logo field in *Config*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: config.logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
}
/**
 * Config document from Prismic
 *
 * - **API ID**: `config`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ConfigDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ConfigDocumentData>, "config", Lang>;
/** Content for Contacts documents */
interface ContactsDocumentData {
    /**
     * address field in *Contacts*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contacts.address
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    address: prismicT.KeyTextField;
    /**
     * phone field in *Contacts*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contacts.phone
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    phone: prismicT.KeyTextField;
}
/**
 * Contacts document from Prismic
 *
 * - **API ID**: `contacts`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ContactsDocumentData>, "contacts", Lang>;
/** Content for Menu documents */
interface MenuDocumentData {
    /**
     * menuItem field in *Menu*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.menuitem[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    menuitem: prismicT.GroupField<Simplify<MenuDocumentDataMenuitemItem>>;
}
/**
 * Item in Menu → menuItem
 *
 */
export interface MenuDocumentDataMenuitemItem {
    /**
     * title field in *Menu → menuItem*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.menuitem[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * link field in *Menu → menuItem*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.menuitem[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    link: prismicT.KeyTextField;
    /**
     * icon field in *Menu → menuItem*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.menuitem[].icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    icon: prismicT.ImageField<never>;
    /**
     * href field in *Menu → menuItem*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.menuitem[].href
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    href: prismicT.LinkToMediaField;
}
/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;
/** Content for Page documents */
interface PageDocumentData {
    /**
     * meta field in *Page*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: page.meta[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    meta: prismicT.GroupField<Simplify<PageDocumentDataMetaItem>>;
    /**
     * url field in *Page*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: page.url[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    url: prismicT.GroupField<Simplify<PageDocumentDataUrlItem>>;
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
}
/**
 * Item in Page → meta
 *
 */
export interface PageDocumentDataMetaItem {
    /**
     * title field in *Page → meta*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.meta[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * description field in *Page → meta*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.meta[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
}
/**
 * Item in Page → url
 *
 */
export interface PageDocumentDataUrlItem {
    /**
     * first field in *Page → url*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.url[].first
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    first: prismicT.KeyTextField;
    /**
     * second field in *Page → url*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.url[].second
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    second: prismicT.KeyTextField;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = TextSlice | ImageWithCaptionSlice | PageHeaderSlice | HeaderWithLinkSlice | CardsSlice | FaqSlice | ImageTextButtonsTwoColsSlice | VideoSlice | StatisticsSlice | FormSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
export type AllDocumentTypes = CardDocument | ConfigDocument | ContactsDocument | MenuDocument | PageDocument;
/**
 * Item in Cards → Items
 *
 */
export interface CardsSliceDefaultItem {
    /**
     * title field in *Cards → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cards.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * description field in *Cards → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cards.items[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * image field in *Cards → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: cards.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * link field in *Cards → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cards.items[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    link: prismicT.KeyTextField;
}
/**
 * Default variation for Cards Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Cards`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CardsSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<CardsSliceDefaultItem>>;
/**
 * Slice variation for *Cards*
 *
 */
type CardsSliceVariation = CardsSliceDefault;
/**
 * Cards Shared Slice
 *
 * - **API ID**: `cards`
 * - **Description**: `Cards`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CardsSlice = prismicT.SharedSlice<"cards", CardsSliceVariation>;
/**
 * Item in Faq → Items
 *
 */
export interface FaqSliceDefaultItem {
    /**
     * answer field in *Faq → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: faq.items[].answer
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    answer: prismicT.RichTextField;
    /**
     * question field in *Faq → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: faq.items[].question
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    question: prismicT.KeyTextField;
}
/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Faq`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FaqSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<FaqSliceDefaultItem>>;
/**
 * Slice variation for *Faq*
 *
 */
type FaqSliceVariation = FaqSliceDefault;
/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: `Faq`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FaqSlice = prismicT.SharedSlice<"faq", FaqSliceVariation>;
/**
 * Primary content in Form → Primary
 *
 */
interface FormSliceDefaultPrimary {
    /**
     * buttonTitle field in *Form → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: form.primary.buttontitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    buttontitle: prismicT.KeyTextField;
    /**
     * buttonVariant field in *Form → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: form.primary.buttonvariant
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    buttonvariant: prismicT.SelectField<"filled" | "filledTonal" | "outlined" | "text">;
}
/**
 * Item in Form → Items
 *
 */
export interface FormSliceDefaultItem {
    /**
     * title field in *Form → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: form.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * sliceExample field in *Form → Items*
     *
     * - **Field Type**: Embed
     * - **Placeholder**: *None*
     * - **API ID Path**: form.items[].sliceexample
     * - **Documentation**: https://prismic.io/docs/core-concepts/embed
     *
     */
    sliceexample: prismicT.EmbedField;
}
/**
 * Default variation for Form Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Form`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FormSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<FormSliceDefaultPrimary>, Simplify<FormSliceDefaultItem>>;
/**
 * Slice variation for *Form*
 *
 */
type FormSliceVariation = FormSliceDefault;
/**
 * Form Shared Slice
 *
 * - **API ID**: `form`
 * - **Description**: `Form`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FormSlice = prismicT.SharedSlice<"form", FormSliceVariation>;
/**
 * Primary content in HeaderWithLink → Primary
 *
 */
interface HeaderWithLinkSliceDefaultPrimary {
    /**
     * Заголовок field in *HeaderWithLink → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Введите заголовок
     * - **API ID Path**: header_with_link.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Описание field in *HeaderWithLink → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Введите описание
     * - **API ID Path**: header_with_link.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Название ссылки field in *HeaderWithLink → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: header_with_link.primary.linktitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    linktitle: prismicT.KeyTextField;
    /**
     * Ссылка field in *HeaderWithLink → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: без домена
     * - **API ID Path**: header_with_link.primary.link
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    link: prismicT.KeyTextField;
}
/**
 * Default variation for HeaderWithLink Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HeaderWithLink`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeaderWithLinkSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeaderWithLinkSliceDefaultPrimary>, never>;
/**
 * Slice variation for *HeaderWithLink*
 *
 */
type HeaderWithLinkSliceVariation = HeaderWithLinkSliceDefault;
/**
 * HeaderWithLink Shared Slice
 *
 * - **API ID**: `header_with_link`
 * - **Description**: `HeaderWithLink`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeaderWithLinkSlice = prismicT.SharedSlice<"header_with_link", HeaderWithLinkSliceVariation>;
/**
 * Primary content in ImageTextButtonsTwoCols → Primary
 *
 */
interface ImageTextButtonsTwoColsSliceDefaultPrimary {
    /**
     * Заголовок field in *ImageTextButtonsTwoCols → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Выбирайте h1 или h2
     * - **API ID Path**: image_text_buttons_two_cols.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *ImageTextButtonsTwoCols → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: image_text_buttons_two_cols.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * image field in *ImageTextButtonsTwoCols → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: image_text_buttons_two_cols.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * imageLeft field in *ImageTextButtonsTwoCols → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: image_text_buttons_two_cols.primary.imageleft
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    imageleft: prismicT.BooleanField;
}
/**
 * Item in ImageTextButtonsTwoCols → Items
 *
 */
export interface ImageTextButtonsTwoColsSliceDefaultItem {
    /**
     * title field in *ImageTextButtonsTwoCols → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: image_text_buttons_two_cols.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * link field in *ImageTextButtonsTwoCols → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: image_text_buttons_two_cols.items[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    link: prismicT.KeyTextField;
    /**
     * variant field in *ImageTextButtonsTwoCols → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: image_text_buttons_two_cols.items[].variant
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    variant: prismicT.SelectField<"filled" | "filledTonal" | "outlined" | "text" | "underscored">;
}
/**
 * Default variation for ImageTextButtonsTwoCols Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ImageTextButtonsTwoCols`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageTextButtonsTwoColsSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ImageTextButtonsTwoColsSliceDefaultPrimary>, Simplify<ImageTextButtonsTwoColsSliceDefaultItem>>;
/**
 * Primary content in ImageTextButtonsTwoCols → Primary
 *
 */
interface ImageTextButtonsTwoColsSliceLeftImageTextButtonsTwoColsPrimary {
    /**
     * Title field in *ImageTextButtonsTwoCols → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: image_text_buttons_two_cols.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *ImageTextButtonsTwoCols → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: image_text_buttons_two_cols.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * image field in *ImageTextButtonsTwoCols → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: image_text_buttons_two_cols.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Item in ImageTextButtonsTwoCols → Items
 *
 */
export interface ImageTextButtonsTwoColsSliceLeftImageTextButtonsTwoColsItem {
    /**
     * title field in *ImageTextButtonsTwoCols → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: image_text_buttons_two_cols.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * link field in *ImageTextButtonsTwoCols → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: image_text_buttons_two_cols.items[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    link: prismicT.KeyTextField;
}
/**
 * LeftImageTextButtonsTwoCols variation for ImageTextButtonsTwoCols Slice
 *
 * - **API ID**: `leftImageTextButtonsTwoCols`
 * - **Description**: `ImageTextButtonsTwoCols`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageTextButtonsTwoColsSliceLeftImageTextButtonsTwoCols = prismicT.SharedSliceVariation<"leftImageTextButtonsTwoCols", Simplify<ImageTextButtonsTwoColsSliceLeftImageTextButtonsTwoColsPrimary>, Simplify<ImageTextButtonsTwoColsSliceLeftImageTextButtonsTwoColsItem>>;
/**
 * Slice variation for *ImageTextButtonsTwoCols*
 *
 */
type ImageTextButtonsTwoColsSliceVariation = ImageTextButtonsTwoColsSliceDefault | ImageTextButtonsTwoColsSliceLeftImageTextButtonsTwoCols;
/**
 * ImageTextButtonsTwoCols Shared Slice
 *
 * - **API ID**: `image_text_buttons_two_cols`
 * - **Description**: `ImageTextButtonsTwoCols`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageTextButtonsTwoColsSlice = prismicT.SharedSlice<"image_text_buttons_two_cols", ImageTextButtonsTwoColsSliceVariation>;
/**
 * Primary content in ImageWithCaption → Primary
 *
 */
interface ImageWithCaptionSliceDefaultPrimary {
    /**
     * Image field in *ImageWithCaption → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: image_with_caption.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Caption field in *ImageWithCaption → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: image_with_caption.primary.caption
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    caption: prismicT.KeyTextField;
}
/**
 * Default variation for ImageWithCaption Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ImageWithCaption`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageWithCaptionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ImageWithCaptionSliceDefaultPrimary>, never>;
/**
 * Slice variation for *ImageWithCaption*
 *
 */
type ImageWithCaptionSliceVariation = ImageWithCaptionSliceDefault;
/**
 * ImageWithCaption Shared Slice
 *
 * - **API ID**: `image_with_caption`
 * - **Description**: `ImageWithCaption`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageWithCaptionSlice = prismicT.SharedSlice<"image_with_caption", ImageWithCaptionSliceVariation>;
/**
 * Primary content in PageHeader → Primary
 *
 */
interface PageHeaderSliceDefaultPrimary {
    /**
     * Заголовок field in *PageHeader → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Напишите заголовок страницы
     * - **API ID Path**: page_header.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *PageHeader → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: page_header.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for PageHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: `PageHeader`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PageHeaderSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<PageHeaderSliceDefaultPrimary>, never>;
/**
 * Slice variation for *PageHeader*
 *
 */
type PageHeaderSliceVariation = PageHeaderSliceDefault;
/**
 * PageHeader Shared Slice
 *
 * - **API ID**: `page_header`
 * - **Description**: `PageHeader`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PageHeaderSlice = prismicT.SharedSlice<"page_header", PageHeaderSliceVariation>;
/**
 * Item in Statistics → Items
 *
 */
export interface StatisticsSliceDefaultItem {
    /**
     * value field in *Statistics → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: statistics.items[].value
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    value: prismicT.KeyTextField;
    /**
     * description field in *Statistics → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: statistics.items[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
}
/**
 * Default variation for Statistics Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Statistics`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type StatisticsSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<StatisticsSliceDefaultItem>>;
/**
 * Slice variation for *Statistics*
 *
 */
type StatisticsSliceVariation = StatisticsSliceDefault;
/**
 * Statistics Shared Slice
 *
 * - **API ID**: `statistics`
 * - **Description**: `Statistics`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type StatisticsSlice = prismicT.SharedSlice<"statistics", StatisticsSliceVariation>;
/**
 * Primary content in Text → Primary
 *
 */
interface TextSliceDefaultPrimary {
    /**
     * Content field in *Text → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: text.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
}
/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Text`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TextSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Text*
 *
 */
type TextSliceVariation = TextSliceDefault;
/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: `Text`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextSlice = prismicT.SharedSlice<"text", TextSliceVariation>;
/**
 * Primary content in Video → Primary
 *
 */
interface VideoSliceDefaultPrimary {
    /**
     * url field in *Video → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: video.primary.url
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    url: prismicT.KeyTextField;
}
/**
 * Default variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Video`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VideoSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<VideoSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Video*
 *
 */
type VideoSliceVariation = VideoSliceDefault;
/**
 * Video Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: `Video`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VideoSlice = prismicT.SharedSlice<"video", VideoSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { CardDocumentData, CardDocument, ConfigDocumentData, ConfigDocument, ContactsDocumentData, ContactsDocument, MenuDocumentData, MenuDocumentDataMenuitemItem, MenuDocument, PageDocumentData, PageDocumentDataMetaItem, PageDocumentDataUrlItem, PageDocumentDataSlicesSlice, PageDocument, AllDocumentTypes, CardsSliceDefaultItem, CardsSliceDefault, CardsSliceVariation, CardsSlice, FaqSliceDefaultItem, FaqSliceDefault, FaqSliceVariation, FaqSlice, FormSliceDefaultPrimary, FormSliceDefaultItem, FormSliceDefault, FormSliceVariation, FormSlice, HeaderWithLinkSliceDefaultPrimary, HeaderWithLinkSliceDefault, HeaderWithLinkSliceVariation, HeaderWithLinkSlice, ImageTextButtonsTwoColsSliceDefaultPrimary, ImageTextButtonsTwoColsSliceDefaultItem, ImageTextButtonsTwoColsSliceDefault, ImageTextButtonsTwoColsSliceLeftImageTextButtonsTwoColsPrimary, ImageTextButtonsTwoColsSliceLeftImageTextButtonsTwoColsItem, ImageTextButtonsTwoColsSliceLeftImageTextButtonsTwoCols, ImageTextButtonsTwoColsSliceVariation, ImageTextButtonsTwoColsSlice, ImageWithCaptionSliceDefaultPrimary, ImageWithCaptionSliceDefault, ImageWithCaptionSliceVariation, ImageWithCaptionSlice, PageHeaderSliceDefaultPrimary, PageHeaderSliceDefault, PageHeaderSliceVariation, PageHeaderSlice, StatisticsSliceDefaultItem, StatisticsSliceDefault, StatisticsSliceVariation, StatisticsSlice, TextSliceDefaultPrimary, TextSliceDefault, TextSliceVariation, TextSlice, VideoSliceDefaultPrimary, VideoSliceDefault, VideoSliceVariation, VideoSlice };
    }
}
